Implement basic functionality
Plakhotenko/to-do-list pull request #1
Opened 2023-01-15 20:36 UTC by Plakhotenko

2023-01-20 11:02 UTC, Rammfall requested changes

2023-01-20 11:02 UTC, Rammfall commented on src/App.tsx
> +          isComplete: true,
You was created hook useTasks, maybe you return you handlers from the hook, and in component you can use only handlers, without implementation

2023-01-20 11:02 UTC, Rammfall commented on src/App.tsx
> +        <CreateTaskForm onNewTaskCreate={onNewTaskCreate} />
Great, you set props with function, which adding to state. Often people send setState func in props

2023-01-20 14:17 UTC, Plakhotenko commented on src/App.tsx
> +          isComplete: true,
fixed

2023-01-21 11:21 UTC, Rammfall approved these changes

2023-01-21 14:21 UTC, merged